add python3-dev to install.sh (#720)
to prevent fail during installation:

``` 
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-secur
ity -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c Le
venshtein/_levenshtein.c -o build/temp.linux-x86_64-3.9/Levenshtein/_levenshtein.o
      Levenshtein/_levenshtein.c:99:10: fatal error: Python.h: No such file or directory
         99 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
```